### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by joyol** [guaguaguaxia/weekly_report#15]
```
> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 1048 ms (215 modules)
wait  - compiling...
event - compiled successfully in 109 ms (178 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 241 ms (641 modules)
Streamed response:
wait  - compiling /api/generate (client and server)...
event - compiled successfully in 31 ms (43 modules)
wait  - compiling /_error (client and server)...
error - Error: Missing env var from OpenAI
    at <unknown> (webpack-internal:///(middleware)/./pages/api/generate.ts:10)
    at eval (webpack-internal:///(middleware)/./pages/api/generate.ts:10:15)
    at Module.(middleware)/./pages/api/generate.ts (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:195:1)
    at __webpack_require__ (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:257:21)
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CProject%5Cweekly_report%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CProject%5Cweekly_report!:11:19)
    at Module.(middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CProject%5Cweekly_report%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CProject%5Cweekly_report! (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:19:1)
    at __webpack_require__ (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:37:33)
    at __webpack_exec__ (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:355:48)
    at <unknown> (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:356:37)
    at webpackJsonpCallback (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:1117:39)
event - compiled client and server successfully in 114 ms (642 modules)
Streamed response:
error - Error: Missing env var from OpenAI
    at <unknown> (webpack-internal:///(middleware)/./pages/api/generate.ts:10)
    at eval (webpack-internal:///(middleware)/./pages/api/generate.ts:10:15)
    at Module.(middleware)/./pages/api/generate.ts (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:195:1)
    at __webpack_require__ (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:257:21)
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CProject%5Cweekly_report%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CProject%5Cweekly_report!:11:19)
    at Module.(middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CProject%5Cweekly_report%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CProject%5Cweekly_report! (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:19:1)
    at __webpack_require__ (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:37:33)
    at __webpack_exec__ (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:355:48)
    at <unknown> (file://D:\Project\weekly_report\.next\server\pages\api\generate.js:356:37)
    at webpackJsonpCallback (file://D:\Project\weekly_report\.next\server\edge-runtime-webpack.js:1117:39)


```

**Comment by guaguaguaxia** [comment]
Missing env var from OpenAI

**Comment by guaguaguaxia** [comment]
你把.env.example文件改成.env，再按要求配置参数，具体看README

**Comment by joyol** [comment]
> 你把.env.example文件改成.env，再按要求配置参数，具体看README

文件名没改，跑通了，感谢！
做后端的，对OpenAI不熟
