### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by shenyaocan** [guaguaguaxia/weekly_report#23]
![1676443183208](https://user-images.githubusercontent.com/39956271/218952152-e41d2f18-8bb5-429b-9ce6-da8cd8549592.png)

**Comment by guaguaguaxia** [comment]
需要配置OPEN_AI_KEY，你再看看README

**Comment by shenyaocan** [comment]
error - Error: Missing env var from OpenAI
    at <unknown> (webpack-internal:///(middleware)/./pages/api/generate.ts:10)
    at eval (webpack-internal:///(middleware)/./pages/api/generate.ts:10:15)
    at (middleware)/./pages/api/generate.ts (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:195:1)
    at __webpack_require__ (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:257:21)
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CChatGPT%5Cweekly_report-main%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CChatGPT%5Cweekly_report-main!:11:19)
    at (middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CChatGPT%5Cweekly_report-main%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CChatGPT%5Cweekly_report-main! (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:19:1)
    at __webpack_require__ (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:37:33)
    at __webpack_exec__ (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:355:48)
    at <unknown> (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:356:37)
    at webpackJsonpCallback (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:1117:39)

**Comment by shenyaocan** [comment]
Streamed response:

error - Error: Missing env var from OpenAI

    at <unknown> (webpack-internal:///(middleware)/./pages/api/generate.ts:10)

    at eval (webpack-internal:///(middleware)/./pages/api/generate.ts:10:15)

    at (middleware)/./pages/api/generate.ts (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:195:1)

    at __webpack_require__ (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:37:33)

    at fn (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:257:21)

    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CChatGPT%5Cweekly_report-main%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CChatGPT%5Cweekly_report-main!:11:19)

    at (middleware)/./node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=D%3A%5CChatGPT%5Cweekly_report-main%5Cpages%5Capi%5Cgenerate.ts&page=%2Fapi%2Fgenerate&rootDir=D%3A%5CChatGPT%5Cweekly_report-main! (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:19:1)

    at __webpack_require__ (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:37:33)

    at __webpack_exec__ (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:355:48)

    at <unknown> (file://D:\ChatGPT\weekly_report-main\.next\server\pages\api\generate.js:356:37)

    at webpackJsonpCallback (file://D:\ChatGPT\weekly_report-main\.next\server\edge-runtime-webpack.js:1117:39)







--

-------------------------------------------------------------
沈耀灿
186-6570-1237





在 2023-02-15 14:45:06，"guaguaguaxia" ***@***.***> 写道：

需要配置OPEN_AI_KEY，你再看看README

**Comment by shenyaocan** [comment]
一直loading，怎么完成不了！！！

![image](https://user-images.githubusercontent.com/39956271/219049670-e1bfbaf3-ec1b-433a-960f-d60e8009b760.png)

**Comment by furunhao** [comment]
把本地文件 `.env.example` 要改成 `.env `
请问这个步骤完成了吗，我也是跟你一样的情况，根据README里的内容，执行了这个操作就正常了
