### ISSUE TITLE
提示“服务繁忙，请稍后再试”

### ISSUE THREAD

**Issue by laochenfei233** [guaguaguaxia/weekly_report#57]
在vercel构建完成以后生成日报后提示“服务繁忙，请稍后再试”，log显示以下问题：
`Error: Missing env var from OpenAI
    at (pages/api/generate.ts:5:10)
    at (webpack/bootstrap:21:0)
    at ([native code])
    at (webpack/bootstrap:21:0)
    at (pages/api/generate.ts:46:15)
    at (webpack/runtime/jsonp chunk loading:34:0)
    at (api/generate:middleware.js:1:17)`
请问是我key输入问题还是其他的问题？

**Comment by guaguaguaxia** [comment]
Error: Missing env var from OpenAI
没有找到key，你是本地部署的吗？需要把配置文件改下名称，请再看看readme

**Comment by laochenfei233** [comment]
配置文件改了，还是没用，还换了几个token。
不过根据你readme发的那个一键重新建立了一下，能正常运行了
