### ISSUE TITLE
我在访问地址时遇到了问题！缺少模块文件，请问这是为什么

### ISSUE THREAD

**Issue by furunhao** [guaguaguaxia/weekly_report#9]
```html
> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 1548 ms (214 modules)
wait  - compiling...
event - compiled successfully in 146 ms (177 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 596 ms (636 modules)
error - Error: Cannot find module './undefined.json'
    at webpackContextResolve (D:\Users\Run\WebstormProjects\weekly_report\.next\server\pages\index.js:33:11)
    at webpackContext (D:\Users\Run\WebstormProjects\weekly_report\.next\server\pages\index.js:28:11)
    at getStaticProps (webpack-internal:///./pages/index.tsx:435:86)
    at Object.renderToHTML (D:\Users\Run\WebstormProjects\weekly_report\node_modules\next\dist\server\render.js:385:26)
    at async doRender (D:\Users\Run\WebstormProjects\weekly_report\node_modules\next\dist\server\base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (D:\Users\Run\WebstormProjects\weekly_report\node_modules\next\dist\server\base-server.js:837:28)
    at async D:\Users\Run\WebstormProjects\weekly_report\node_modules\next\dist\server\response-cache\index.js:83:36 {
  code: 'MODULE_NOT_FOUND',
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 102 ms (637 modules)

```

**Comment by guaguaguaxia** [comment]
你好，我不是很熟悉前端知识，暂时只知道基础的操作。但是你的这个问题似乎谷歌可解：https://stackoverflow.com/questions/47083351/node-module-not-found

**Comment by furunhao** [comment]
感谢你的回复，我尝试了链接里的方法，还未解决，我去尝试一下其他方法
